var settings = {
    'adsafe': 'true if ADsafe rules should be enfored',
    'bitwise': 'true if bitwise operations sould be allowed',
    'browser': 'true if the standard browser globals should be predefined',
    'cap' : 'true if uppercase HTML should be allowed',
    'confusion': 'true if variables and properties are allowed to contain more than one type of value',
    'continue': 'true if the continue statement should be allowed',
    'css': 'true if CSS workarounds should be tolerated',
    'debug': 'true if debugger statements should be allowed.',
    'devel': 'true if browser globals that are useful in development should be predefined',
    'eqeq': 'true if the == and != operators should be tolerated.',
    'es5': 'if ES5 syntax should be allowed',
    'evil': 'true if eval should be allowed',
    'forin': 'true if unfiltered for in statements should be allowed',
    'fragment': 'true if HTML fragments should be allowed',
    'indent': 'The number of spaces used for indentation (default is 4)',
    'maxerr': 'The maximum number of warnings reported (default is 1000)',
    'maxlen': 'The maximum number of characters in a line',
    'newcap': 'true if Initial Caps with constructor functions is optional',
    'node': 'true if Node.js globals should be predefined',
    'nomen': 'true if names should not be checked for initial or trailing underbars',
    'on': 'true if HTML event handlers should be allowed',
    'passfail': 'true if the scan should stop on first error',
    'plusplus': 'true if ++ and -- should be allowed',
    'predef': 'comma-separated list of predefined global variables',
    'regexp': 'true if . and [^...] should be allowed in RegExp literals',
    'rhino': 'true if the Rhino environment globals should be predefined',
    'safe': 'true if the safe subset rules are enforced',
    'sloppy': 'true if the ES5 \'use strict\'; pragma is not required',
    'sub': 'true if subscript notation may be used for expressions better expressed in dot notation',
    'undef': 'true if variables and functions need not be declared before used',
    'unparam': 'true if warnings should not be given for unused parameters',
    'vars': 'true if multiple var statement per function should be allowed',
    'white': 'true if strict whitespace rules should be ignored',
    'widget': 'true if the Yahoo Widgets globals should be predefined',
    'windows': 'true if the Windows globals should be predefined'
};
